// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SuperChess.Api.Data;

#nullable disable

namespace SuperChess.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518224000_AddBotPlayers")]
    partial class AddBotPlayers
    {
    }
}
