// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SuperChess.Api.Data;

#nullable disable

namespace SuperChess.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519093000_AddRefreshTokenSession")]
    partial class AddRefreshTokenSession
    {
    }
}
